name: 'Prepare clojure env'
description: 'Prepare clojure environment for build'
runs:
  using: "composite"
  steps:
    - name: Cache local Maven repository
      uses: actions/cache@v4
      id: maven-cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        lein: 2.9.10
        clj-kondo: 'latest'

    - name: Install Clojure deps
      run: lein deps
      env:
        GITHUB_USERNAME: ${{ github.actor }}
        GITHUB_REGISTRY_TOKEN: ${{ github.token }}
      if: steps.maven-cache.outputs.cache-hit != 'true'
      shell: bash
