sudo: required
language: clojure
jdk:
  - openjdk11
services:
  - docker
install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: Mert3xJFIL3mf3OMmWAhxS9jsu/44d3w7CocbfXUJIlSNWCqbD7DZjK9xCgzoBf2FRiqoHg/wGYYRbU1FjaBOgzBR+TVhC4KG+1x4vi/mkSZnv3r4iSzTncD9z9yqoXIHMy7knagFMBPwZdm8DYFwnPYARkzNEmA5dPShfF4t8pmYAFDLF2sOLhBOeFRbbM7n8DlBhbiRblBQV5yXEzew91At41BsmsB8QZP468JE/9UPd/2MWFDUfbwQ/LPTqMe8EQGwbeFRvKUMD5OTAVmqeydXEFkf/pw4BWa1C7wd1xC5t/GjYnWAo35ChV+gKVLZKfNwqyxfWzp++ZWLvbKpxL5TWJZ4ja0vi0nqzd45xPV8Qsk2/bfbyFD6y1xWCFV/Oa3BBNWiuDXBGd+Oi4pZcuiXvUfeHGTr793/O9QHgsSmxvJH72eNLpk40vMPQ5mrV0Fj+caf06K87SDWyCUIOthHcunKP8jSOgk5zP+ZAKsCNRw+X3bKZOvlkmWCdkdzJBs5k0fCVcW6cTHtogoQa9NU1P1fQuMs3wckW+ZLevSnQjQYpbHSeNoj8bkn+dfQ/GQDHGBzEswAAcvCeLME5WMFeF8/TJAMlF8lZrspgty73yUdjtCFNfdLrt+FikysHsTvPrabzZUX64OAHZabWgy9jwhAh7fzl3TM8JIgZI=
    # AWS_SECRET_ACCESS_KEY
    - secure: xOaexZ4qKTQWiK8AOvSpW3QG0K954uwFy239Q0DCyGee42xXX3uRWWBVYO49MhLnoc6+A8cKYSNXtEatvopyy4unseGjCYflQ9lJs0Qhg3ue/fscdvG2tp7EqjlYwDjlDIgQ3KESO34ZwLsi3TSFHES8rwLEZSrn86PrEVk5nMDCztwXfTC/JsiV6raPCdLRSaXBf9djuVHaT7fyDhxFmebJAY9n7JMFJvVhP3wDnWwKqpx7BSFUhA5fsV/XUj9k9wVwKgjwGL0WUBgb659MGpOl0SDsJtVIGCfNOwd+9PgPz6U7hWRqqOFQtP6RHs2xXjN016lvJ4PBBhDUYfxwpMQWemA7CmOLFgfQ+OKLOlbdtpUIhbUBn4ZtN65BdQ/LrSdsvtpQmmkYoxfBwYD96dPK5EI6RDmbwFURpW3f0nSzdwksk44yK1S4KZLvTJhonJl3Fbc81sIo0VBX1DXWhjDyoQvdfyI5a5eCmskWYI7WJonNmEUeu76txFTx0BMJEBmAlXRaSliQLD8UmFZSwklBt7M8GBRHc3Gb6aRMCeHj7apdZ0IAKeXA3w7UJdJRmQxXn5qrb0VZ6lU5G19ePMf6BOXQa5eI6JWHyZifyHkrRX1WJAC3i8QncgswnVhwRQbq6PEaUKEIDn42PLPZ9qxQ5mmXahW35ILobdUTTP4=
script:
  - lein test
  - lein uberjar

  - mv target/yki-*-standalone.jar $DOCKER_BUILD_DIR/artifact/yki.jar
  - cp -vr oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-fatjar-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-fatjar.sh yki

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh yki
  on:
    all_branches: true

git:
  depth: false

notifications:
  flowdock:
    secure: "p6xQI8bslQFLH9ho9QUAt27MQNvYzy2l75fXEDpTrsIK+nODJFBKrgvBPy/LzrCs7+aEOueabSLMeTQe5vkHRUhRLEDCpgvkXlSYzefkWA9K1nPPeJSbpn4Hkj58ntgfGCt7o9hGEuNi0zAMy4gmd5WITT6e+mNxFixy7QaDTjPzmIPVDs2rlyXYTLAF7uZAkdvw1TVY8OX5xf8iyTPVVr+D21uHNCqpsSlghvC2mFemgWchBbqXcCkd1bgOHr3Ev2+1YHqWm6Ee1jM0LSwmWhyZ/vq29WcZMCkMxrWrYqxIaIhB290iflz3lhYiaJU1szYCYcevmQRJ6AVryNkR9c+FGWfDtiBPVEGUZ9kbkhNk/xQwTNIPy1iuHiNyEPKfbeG3W1Kwei0O3HSeGIUX8f3i2S5IHZHOtYRExqXH6IAb7NeJXnZRWCW6jUGZtqIj1BYUAdfENM++6JhUultLz76ii41GL0vvZkRNZts4lg3JcxKxNHTExnLZvi8RzxGjyPkoAkkmCObSqaL/hVqLUWw577xBtRlniNMGa1qu9QjBQ/aiQlwbUNjone0pabHTJsnptJRHmmzmjq85kyj5bxGo/Aedrek+pnLUS7LS1+5saIflqaR2+1FDTsnaGXIkc/HYCQsl/WACi29ihgpHL9C8vrC1k5WoRXV7KLlr34I="
