INSERT INTO language(code) VALUES ('fi');
--;;
INSERT INTO language(code) VALUES ('sv');
--;;
INSERT INTO language(code) VALUES ('en');
--;;
INSERT INTO language(code) VALUES ('es');
--;;
INSERT INTO language(code) VALUES ('it');
--;;
INSERT INTO language(code) VALUES ('fr');
--;;
INSERT INTO language(code) VALUES ('se');
--;;
INSERT INTO language(code) VALUES ('de');
--;;
INSERT INTO language(code) VALUES ('ru');
--;;
INSERT INTO exam_level(code) VALUES ('PERUS');
--;;
INSERT INTO exam_level(code) VALUES ('KESKI');
--;;
INSERT INTO exam_level(code) VALUES ('YLIN');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-01-27', '2017-12-01', '2017-12-08');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-01-27'), 'fi');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-10-27', '2018-09-03', '2018-09-28');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-10-27'), 'en');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-11-10', '2018-09-03', '2018-09-28');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-10'), 'fi');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-11-17', '2018-09-03', '2018-09-28');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-17'), 'es');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-17'), 'se');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-17'), 'de');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2019-01-26', '2018-12-03', '2018-12-14');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2019-01-26'), 'fi');
--;;

