INSERT INTO language(code) VALUES ('fin');
--;;
INSERT INTO language(code) VALUES ('swe');
--;;
INSERT INTO language(code) VALUES ('eng');
--;;
INSERT INTO language(code) VALUES ('spa');
--;;
INSERT INTO language(code) VALUES ('ita');
--;;
INSERT INTO language(code) VALUES ('fra');
--;;
INSERT INTO language(code) VALUES ('sme');
--;;
INSERT INTO language(code) VALUES ('deu');
--;;
INSERT INTO language(code) VALUES ('rus');
--;;
INSERT INTO exam_level(code) VALUES ('PERUS');
--;;
INSERT INTO exam_level(code) VALUES ('KESKI');
--;;
INSERT INTO exam_level(code) VALUES ('YLIN');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-01-27', '2017-12-01', '2017-12-08');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-01-27'), 'fin');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-10-27', '2018-09-03', '2018-09-28');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-10-27'), 'eng');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-11-10', '2018-09-03', '2018-09-28');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-10'), 'fin');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2018-11-17', '2018-09-03', '2018-09-28');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-17'), 'spa');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-17'), 'sme');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2018-11-17'), 'deu');
--;;
INSERT INTO exam_date(exam_date, registration_start_date, registration_end_date) VALUES ('2019-01-26', '2018-12-03', '2018-12-14');
--;;
INSERT INTO exam_date_language(exam_date_id, language_code) VALUES ((SELECT id FROM exam_date WHERE exam_date = '2019-01-26'), 'fin');
--;;

